'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gatekeeper_Suite_2016.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property amberball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amberball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=CHECKMOBILE.
        '''</summary>
        Public ReadOnly Property CHECKMOBILE() As String
            Get
                Return ResourceManager.GetString("CHECKMOBILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=CHECKONLINE.
        '''</summary>
        Public ReadOnly Property CHECKONLINE() As String
            Get
                Return ResourceManager.GetString("CHECKONLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=CHECKPRIV.
        '''</summary>
        Public ReadOnly Property CHECKPRIV() As String
            Get
                Return ResourceManager.GetString("CHECKPRIV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \motd.rtf.
        '''</summary>
        Public ReadOnly Property DefaultTextFilename() As String
            Get
                Return ResourceManager.GetString("DefaultTextFilename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=FORCELOGOUT.
        '''</summary>
        Public ReadOnly Property FORCELOGOUT() As String
            Get
                Return ResourceManager.GetString("FORCELOGOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=GETALLPRINTERS.
        '''</summary>
        Public ReadOnly Property GETALLPRINTERS() As String
            Get
                Return ResourceManager.GetString("GETALLPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=GETLOGINRTF.
        '''</summary>
        Public ReadOnly Property GETLOGINRTF() As String
            Get
                Return ResourceManager.GetString("GETLOGINRTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=GETMYPRINTERS.
        '''</summary>
        Public ReadOnly Property GETMYPRINTERS() As String
            Get
                Return ResourceManager.GetString("GETMYPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=GETPRIVFILE.
        '''</summary>
        Public ReadOnly Property GETPRIVFILE() As String
            Get
                Return ResourceManager.GetString("GETPRIVFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property greenball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=LATCHGATEKEEPER.
        '''</summary>
        Public ReadOnly Property LATCHGATEKEEPER() As String
            Get
                Return ResourceManager.GetString("LATCHGATEKEEPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \privfile.txt.
        '''</summary>
        Public ReadOnly Property LocalPrivFile() As String
            Get
                Return ResourceManager.GetString("LocalPrivFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LoginBoxFlat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginBoxFlat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LoginBoxWhiteCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginBoxWhiteCopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=MAPMYPRINTERS.
        '''</summary>
        Public ReadOnly Property MAPMYPRINTERS() As String
            Get
                Return ResourceManager.GetString("MAPMYPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=MAPTHESEPRINTERS.
        '''</summary>
        Public ReadOnly Property MAPTHESEPRINTERS() As String
            Get
                Return ResourceManager.GetString("MAPTHESEPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=MTREDIRECT.
        '''</summary>
        Public ReadOnly Property MTREDIRECT() As String
            Get
                Return ResourceManager.GetString("MTREDIRECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=NOMTREDIRECT.
        '''</summary>
        Public ReadOnly Property NOMTREDIRECT() As String
            Get
                Return ResourceManager.GetString("NOMTREDIRECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PrintboxWhiteCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintboxWhiteCopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PrinterChooser.exe.
        '''</summary>
        Public ReadOnly Property PrinterChooserExe() As String
            Get
                Return ResourceManager.GetString("PrinterChooserExe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=PROCESSPRIV.
        '''</summary>
        Public ReadOnly Property PROCESSPRIV() As String
            Get
                Return ResourceManager.GetString("PROCESSPRIV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=RECORDLOGIN&amp;username=.
        '''</summary>
        Public ReadOnly Property RECORDLOGIN() As String
            Get
                Return ResourceManager.GetString("RECORDLOGIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property redball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=SETAPPDATA.
        '''</summary>
        Public ReadOnly Property SETAPPDATA() As String
            Get
                Return ResourceManager.GetString("SETAPPDATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=SETSID&amp;sid=.
        '''</summary>
        Public ReadOnly Property SETSID() As String
            Get
                Return ResourceManager.GetString("SETSID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=USER&amp;username=.
        '''</summary>
        Public ReadOnly Property SETUSER() As String
            Get
                Return ResourceManager.GetString("SETUSER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=SETUSERPRINTERS&amp;plist=.
        '''</summary>
        Public ReadOnly Property SETUSERPRINTERS() As String
            Get
                Return ResourceManager.GetString("SETUSERPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://localhost:6510/?command=UNLATCHGATEKEEPER.
        '''</summary>
        Public ReadOnly Property UNLATCHGATEKEEPER() As String
            Get
                Return ResourceManager.GetString("UNLATCHGATEKEEPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Windows\DesktopWallpaper\desktop2.jpg.
        '''</summary>
        Public ReadOnly Property wallpaperFilename() As String
            Get
                Return ResourceManager.GetString("wallpaperFilename", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
