'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Middleman2016.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPUPDATE.
        '''</summary>
        Friend ReadOnly Property GPUPDATE() As String
            Get
                Return ResourceManager.GetString("GPUPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \priv.txt.
        '''</summary>
        Friend ReadOnly Property LocalPrivFile() As String
            Get
                Return ResourceManager.GetString("LocalPrivFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to qHhzqsFNwn.
        '''</summary>
        Friend ReadOnly Property LOCK() As String
            Get
                Return ResourceManager.GetString("LOCK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hw4uLegSH7.
        '''</summary>
        Friend ReadOnly Property MSG() As String
            Get
                Return ResourceManager.GetString("MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6AUpuPB4dP.
        '''</summary>
        Friend ReadOnly Property PRINTER() As String
            Get
                Return ResourceManager.GetString("PRINTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to q5gfuChcVs.
        '''</summary>
        Friend ReadOnly Property PRINTERDEFAULT() As String
            Get
                Return ResourceManager.GetString("PRINTERDEFAULT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CHECKMOBILE.
        '''</summary>
        Friend ReadOnly Property wsCHECKMOBILE() As String
            Get
                Return ResourceManager.GetString("wsCHECKMOBILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CHECKONLINE.
        '''</summary>
        Friend ReadOnly Property wsCHECKONLINE() As String
            Get
                Return ResourceManager.GetString("wsCHECKONLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CHECKPRIV.
        '''</summary>
        Friend ReadOnly Property wsCHECKPRIV() As String
            Get
                Return ResourceManager.GetString("wsCHECKPRIV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FORCELOGOUT.
        '''</summary>
        Friend ReadOnly Property wsFORCELOGOUT() As String
            Get
                Return ResourceManager.GetString("wsFORCELOGOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETALLPRINTERS.
        '''</summary>
        Friend ReadOnly Property wsGETALLPRINTERS() As String
            Get
                Return ResourceManager.GetString("wsGETALLPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETLOGINRTF.
        '''</summary>
        Friend ReadOnly Property wsGETLOGINRTF() As String
            Get
                Return ResourceManager.GetString("wsGETLOGINRTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETMYPRINTERS.
        '''</summary>
        Friend ReadOnly Property wsGETMYPRINTERS() As String
            Get
                Return ResourceManager.GetString("wsGETMYPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETPRIVFILE.
        '''</summary>
        Friend ReadOnly Property wsGETPRIVFILE() As String
            Get
                Return ResourceManager.GetString("wsGETPRIVFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETUSERID.
        '''</summary>
        Friend ReadOnly Property wsGETUSERID() As String
            Get
                Return ResourceManager.GetString("wsGETUSERID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETVERSION.
        '''</summary>
        Friend ReadOnly Property wsGETVERSION() As String
            Get
                Return ResourceManager.GetString("wsGETVERSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LATCHGATEKEEPER.
        '''</summary>
        Friend ReadOnly Property wsLATCHGATEKEEPER() As String
            Get
                Return ResourceManager.GetString("wsLATCHGATEKEEPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LOCK.
        '''</summary>
        Friend ReadOnly Property wsLOCK() As String
            Get
                Return ResourceManager.GetString("wsLOCK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MAPMYPRINTERS.
        '''</summary>
        Friend ReadOnly Property wsMAPMYPRINTERS() As String
            Get
                Return ResourceManager.GetString("wsMAPMYPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MAPTHESEPRINTERS.
        '''</summary>
        Friend ReadOnly Property wsMAPTHESEPRINTERS() As String
            Get
                Return ResourceManager.GetString("wsMAPTHESEPRINTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSG.
        '''</summary>
        Friend ReadOnly Property wsMSG() As String
            Get
                Return ResourceManager.GetString("wsMSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PROCESSPRIV.
        '''</summary>
        Friend ReadOnly Property wsPROCESSPRIV() As String
            Get
                Return ResourceManager.GetString("wsPROCESSPRIV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RECORDLOGIN.
        '''</summary>
        Friend ReadOnly Property wsRECORDLOGIN() As String
            Get
                Return ResourceManager.GetString("wsRECORDLOGIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to REG.
        '''</summary>
        Friend ReadOnly Property wsREG() As String
            Get
                Return ResourceManager.GetString("wsREG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RUN.
        '''</summary>
        Friend ReadOnly Property wsRUN() As String
            Get
                Return ResourceManager.GetString("wsRUN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SETAPPDATA.
        '''</summary>
        Friend ReadOnly Property wsSETAPPDATA() As String
            Get
                Return ResourceManager.GetString("wsSETAPPDATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SETSID.
        '''</summary>
        Friend ReadOnly Property wsSETSID() As String
            Get
                Return ResourceManager.GetString("wsSETSID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNLATCHGATEKEEPER.
        '''</summary>
        Friend ReadOnly Property wsUNLATCHGATEKEEPER() As String
            Get
                Return ResourceManager.GetString("wsUNLATCHGATEKEEPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USER.
        '''</summary>
        Friend ReadOnly Property wsUSER() As String
            Get
                Return ResourceManager.GetString("wsUSER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WHOAMI.
        '''</summary>
        Friend ReadOnly Property wsWHOAMI() As String
            Get
                Return ResourceManager.GetString("wsWHOAMI", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
